import Head from 'next/head';
import {BsFillMoonStarsFill} from '../node_modules/react-icons/bs';
import {AiFillTwitterCircle, AiFillLinkedin, AiFillYoutube} from '../node_modules/react-icons/ai';
import Image from "next/image";
import deved from '../public/dev-ed-wave.png';
import design from '../public/design.png'
import code from '../public/code.png'
import consulting from '../public/consulting.png'
import web1 from '../public/web1.png'
import web2 from '../public/web2.png'
import web3 from '../public/web3.png'
import web4 from '../public/web4.png'
import web5 from '../public/web5.png'
import web6 from '../public/web6.png'
import { useState } from 'react';

export default function Home() {
  const [darkMode, setDarkMode] = useState(false);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Portafolio de react con nextJs</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className='bg-white px-10 md:px-20 lg:px-40 dark:bg-gray-900'>
      <section className='min-h-screen'>
        <nav className='py-10 mb-12 flex justify-between'>
          <h1 className='text-xl font-burtons dark:text-white'>DesarrolladoLuijo</h1>
          <ul className='flex items-center'>
            <li>
              <BsFillMoonStarsFill onClick={() => setDarkMode(!darkMode)} className='cursor-pointer text-2xl dark:text-white' />
            </li>
            <li><a className='bg-gradient-to-r from-cyan-500 to-teal-500 text-white px-4 py-2 rounded-md ml-8' href="#">Resume</a></li>
          </ul>
        </nav>

        <div className='text-center p-10 py-10'>
          
          <h2 className='text-5xl py-2 text-teal-600 font-medium md:text-6xl'>LuijoPage</h2>
          <h3 className='text-2xl py-1 md:text-3xl dark:text-white'>Diseñador Web | Desarrollador Frontend</h3>
          <p className='text-md py-5 leading-8 text-gray-800md:text-xl max-w-lg mx-auto dark:text-white'>Lorem ipsum dolor, sit amet consectetur adipisicing elit. Atque vitae dolor cupiditate architecto explicabo commodi deserunt corporis quos nemo, eaque </p>
        </div>

        <div className='text-5xl flex justify-center gap-16 py-3 text-gray-600'>
        <AiFillTwitterCircle />
        <AiFillLinkedin />
        <AiFillYoutube />
        </div>

        <div className='relative mx-auto bg-gradient-to-b from-teal-500 rounded-full w-80 h-80 mt-10 overflow-hidden md:w-96 md:h-96'>
          <Image src={deved} alt="Wever" layout="fill" objectFit='cover'/>
        </div>
      </section>

        {/* Section 2 segunda parte del curso.  */}

        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Services I offer</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. <span className='text-teal-500'>Veniam</span> quibusdam reprehenderit expedita <span className='text-teal-500'>voluptate</span> exercitationem, quia, quos voluptates culpa.</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. quibusdam reprehenderit expedita</p>
          </div>

          {/* Sistema de cartas */}
          <div className='lg:flex gap-10'>
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={design} alt="Wever" width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautifful design</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nemo, quidem modi cupiditate
              </p>
              <h4 className='py-4 text-teal-600'>design tooll i use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            {/* Card2 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={code} alt="Wever" width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautifful design</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nemo, quidem modi cupiditate
              </p>
              <h4 className='py-4 text-teal-600'>design tooll i use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
            {/* Card3 */}
            <div className='text-center shadow-lg p-10 rounded-xl my-10 dark:bg-white'>
              <Image src={consulting} alt="Wever" width={100} height={100} />
              <h3 className='text-lg font-medium pt-8 pb-2'>Beautifful design</h3>
              <p className='py-2'>
                Lorem ipsum dolor sit amet consectetur adipisicing elit. Velit nemo, quidem modi cupiditate
              </p>
              <h4 className='py-4 text-teal-600'>design tooll i use</h4>
              <p className='text-gray-800 py-1'>photoshop</p>
              <p className='text-gray-800 py-1'>illustrator</p>
              <p className='text-gray-800 py-1'>Figma</p>
            </div>
          </div>
        </section>
        {/* portfolio section */}
        <section>
          <div>
            <h3 className='text-3xl py-1 dark:text-white'>Portfolio</h3>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. <span className='text-teal-500'>Veniam</span> quibusdam reprehenderit expedita <span className='text-teal-500'>voluptate</span> exercitationem, quia, quos voluptates culpa.</p>
            <p className='text-md py-2 leading-8 text-gray-800 dark:text-white'>Lorem ipsum dolor sit amet consectetur adipisicing elit. quibusdam reprehenderit expedita</p>
          </div>
          <div className='flex flex-col gap-10 py-10 lg:flex-row lg:flex-wrap'>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} 
              height={'100%'} 
              layout="responsive" 
              src={web1} 
              alt="Wever" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} 
              height={'100%'} 
              layout="responsive" 
              src={web2} 
              alt="Wever" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} height={'100%'} 
              layout="responsive" src={web3} 
              alt="Wever" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} 
              height={'100%'} 
              layout="responsive" 
              src={web4} alt="Wever" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} 
              height={'100%'} 
              layout="responsive" 
              src={web5} alt="Wever" />
            </div>
            <div className='basis-1/3 flex-1'>
              <Image 
              className='rounded-lg object-cover' 
              width={'100%'} height={'100%'} 
              layout="responsive" 
              src={web6} 
              alt="Wever" />
            </div>
          </div>
        </section>
      </main>
    </div>
  )
}
